name: DeepRacer Dashboard CI Pipeline # Name of the Project Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - uses: actions/checkout@v3
    # Setup Node
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    # Install the Dependencies
    - name: Install Dependencies
      run: |
        cd deepracer_dashboard
        npm install
    # Run Tests * Currently no tests are present in the code base therefore we expect this step to exit with code 0
    - name: Test
      run: |
        cd deepracer_dashboard
        npm test
    
  Package:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Install Dependencies
      run: |
        cd deepracer_dashboard
        npm install

    - name: Pack
      run : |
        ls

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: deepracer-dash-${{github.sha}}
        path: deepracer_dashboard/deepracer_dashboard-*.tgz
      

    



        