name: DeepRacer Dashboard CI Pipeline # Name of the Project Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  lintTesting:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - uses: actions/checkout@v3
    # Setup Node
    - name: Use Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    # Install the Dependencies
    - name: Install Dependencies
      run: |
        cd deepracer_dashboard
        npm install




        